"""GeneratedImage Entity - Core domain entity for image generation results."""
from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import Optional


class ImageFormat(Enum):
    """Supported image output formats."""
    PNG = "png"
    JPEG = "jpeg"
    WEBP = "webp"


@dataclass(frozen=True)
class GeneratedImage:
    """Domain Entity: Immutable representation of a generated image.
    
    This entity captures all the essential information about an image
    that was generated by the ML pipeline.
    """
    image_id: str
    prompt: str
    negative_prompt: str
    seed: int
    width: int
    height: int
    num_inference_steps: int
    guidance_scale: float
    created_at: datetime
    raw_bytes: bytes
    format: ImageFormat = ImageFormat.PNG
    model_id: Optional[str] = None

    def __post_init__(self) -> None:
        if not self.image_id:
            raise ValueError("image_id cannot be empty")
        if not self.prompt:
            raise ValueError("prompt cannot be empty")
        if self.width <= 0 or self.height <= 0:
            raise ValueError("width and height must be positive")
        if self.num_inference_steps <= 0:
            raise ValueError("num_inference_steps must be positive")
        if self.guidance_scale < 0:
            raise ValueError("guidance_scale cannot be negative")
        if not self.raw_bytes:
            raise ValueError("raw_bytes cannot be empty")

    @property
    def aspect_ratio(self) -> float:
        """Calculate the aspect ratio of the generated image."""
        return self.width / self.height

    @property
    def resolution(self) -> int:
        """Total pixel count of the image."""
        return self.width * self.height
